# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.mailer:
        class: AppBundle\Mailer\AppMailer
        arguments: ['@mailer', '@templating']
    app.badge_subscriber:
        class: AppBundle\Subscriber\BadgeSubscriber
        arguments: ['@app.mailer']
        tags:
            - {name: kernel.event_subscriber}
