<?php

namespace Amacabr2\BadgeBundle\Repository;

use Amacabr2\BadgeBundle\Entity\Badge;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Retourne le badge
     * @param int $userId
     * @param string $action
     * @param int $actionCount
     * @return Badge
     */
    public function findWithUnlockForAction(int $userId, string $action, int $actionCount): Badge {
        return $this->createQueryBuilder('b')
            ->select('b, u')
            ->where('b.actionName = :actionName')
            ->andWhere('b.actionCount = :actionCount')
            ->andWhere('u.user = :userId OR u.user IS NULL')
            ->leftJoin('b.unlocks', 'u')
            ->setParameters(array(
               'actionCount' => $actionCount,
                'actionNAme' => $action,
                'userId' => $userId
            ))
            ->getQuery()
            ->getSingleResult();
    }

}
